console.log('🧪 ChatBar Testing Instructions');
console.log('===============================');
console.log('');
console.log('📋 Steps to test ChatBar functionality:');
console.log('');
console.log('1. Start the app: npm run dev');
console.log('2. Click on the floating orb (purple circle) to open ChatBar');
console.log('3. Type a command like "hello" or "test"');
console.log('4. Press Enter or click Send');
console.log('5. Check the terminal for console logs');
console.log('');
console.log('🔍 Expected logs in terminal:');
console.log('- 🎯 ChatBar: User sent message: [command]');
console.log('- 🔍 ChatBar: electronAPI available: true');
console.log('- 🔍 ChatBar: executeCommand available: true');
console.log('- 🔄 ChatBar: Sending command to main process...');
console.log('- 🎯 Executing command via IPC: "[command]"');
console.log('- ✅ ChatBar: Main process response: [result]');
console.log('- 🤖 ChatBar: AI response: [response]');
console.log('');
console.log('❌ If you see errors, they will be logged with details');
console.log('');
console.log('🚀 Ready to test! Run: npm run dev'); 