name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 22.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run type-check || npx tsc --noEmit
        continue-on-error: true

      - name: Lint
        run: npm run lint || echo "No linter configured"
        continue-on-error: true

      - name: Build main process
        run: npm run build:main || npx tsc -p tsconfig.main.json

      - name: Build renderer
        run: npm run build:renderer || npx vite build

      # - name: Run tests (uncomment if you add tests)
      #   run: npm test 